Feat/tribute
DegenLabHQ/contracts pull request #137
Opened 2023-04-11 14:35 UTC by yuanjunliang

2023-04-12 02:50 UTC, noyyyy commented on src/PortalLib.sol
> +                (PERSHARE_BASE * poolCoinday) -
should calculate coinday when the airdrop is executed. rather than the current coinday.

2023-04-12 02:56 UTC, noyyyy commented on src/interfaces/IRebornPortal.sol
> +        Forward
use another name according to produect.

2023-04-12 02:58 UTC, noyyyy commented on src/RebornPortal.sol
>          _decreaseFromPool(fromTokenId, amount);
Maybe decrease should also have direction

2023-04-12 07:13 UTC, yuanjunliang commented on src/RebornPortal.sol
> +        PortalLib.Pool memory pool
just compute, no storage option

2023-04-12 07:16 UTC, yuanjunliang commented on src/RebornPortal.sol
>          _decreaseFromPool(fromTokenId, amount);
requrement changed

2023-04-12 13:48 UTC, noyyyy requested changes

2023-04-12 13:48 UTC, noyyyy commented on src/PortalLib.sol
> +
I think it's not necessary to calculate pending coinday. Just settle the coinday before `_flattenRewardDebt`. As `_flattenRewardDebt` is only executed when tribute is changed and pending coinday should be settled every time tribute is changed.

2023-04-12 13:48 UTC, noyyyy commented on src/PortalLib.sol
>  }
The pending view function should only read by off chain appliaction. Everytime write operation happens, the pending coinday should be settled.

2023-04-13 02:10 UTC, yuanjunliang commented on src/PortalLib.sol
>  }
what if no operation for a long time before airdrop?

2023-04-13 03:13 UTC, yuanjunliang commented on src/PortalLib.sol
> +
you are right

2023-04-13 05:45 UTC, noyyyy requested changes

2023-04-13 05:45 UTC, noyyyy commented on src/PortalLib.sol
> +            );
reborn and native are usually dropped in different block, so we need two coinday value. ` _toLastHour(block.timestamp)` is not accurate.

2023-04-13 05:45 UTC, noyyyy commented on src/RebornPortal.sol
> +        PortalLib.Pool memory pool
mark it as internal

2023-04-13 06:00 UTC, noyyyy approved these changes

2023-04-13 06:00 UTC, merged