Feat/contract size optimize
DegenLabHQ/contracts pull request #92
Opened 2023-03-21 10:16 UTC by yuanjunliang

2023-04-03 09:58 UTC, noyyyy requested changes
git ignore `build` directory

2023-04-10 05:16 UTC, noyyyy requested changes

2023-04-10 05:16 UTC, noyyyy commented on src/oz/contracts-upgradeable/utils/CountersUpgradeable.sol
delete

2023-04-10 05:16 UTC, noyyyy commented on src/oz/contracts-upgradeable/token/ERC721/utils/ERC721HolderUpgradeable.sol
delete

2023-04-10 05:16 UTC, noyyyy commented on src/oz/contracts-upgradeable/proxy/ClonesUpgradeable.sol
delete

2023-04-10 05:16 UTC, noyyyy commented on src/mock/RankMock.sol
> -    function setTokenIdToTvlRank(uint256 tokenId) public {
why comment

2023-04-10 06:42 UTC, yuanjunliang commented on src/oz/contracts-upgradeable/utils/CountersUpgradeable.sol
used in draft-ERC20PermitUpgradeable.sol

2023-04-10 07:23 UTC, noyyyy requested changes

2023-04-10 07:23 UTC, noyyyy commented on src/RBT.sol
> -import {SafeOwnableUpgradeable} from "@p12/contracts-lib/contracts/access/SafeOwnableUpgradeable.sol";
why  extract `SafeOwnableUpgradeable`. It's our lib package

2023-04-10 07:23 UTC, noyyyy commented on src/oz/contracts-upgradeable/README.md
can be deleted

2023-04-10 07:29 UTC, yuanjunliang commented on src/RBT.sol
> -import {SafeOwnableUpgradeable} from "@p12/contracts-lib/contracts/access/SafeOwnableUpgradeable.sol";
SafeOwnableUpgradeable use @openzeeplin  conflect with oz

2023-04-10 07:58 UTC, noyyyy commented on src/RBT.sol
> -import {SafeOwnableUpgradeable} from "@p12/contracts-lib/contracts/access/SafeOwnableUpgradeable.sol";
get

2023-04-10 07:58 UTC, noyyyy approved these changes

2023-04-10 08:39 UTC, merged